# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec 文件：将 Flow-AI Sidecar 打包为单个 EXE（供 Tauri externalBin 使用）"""

import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_all

FLOW_AI_ROOT = Path(SPECPATH) / ".." / "Flow-AI" / "src"
FLOW_AI_OPEN_ROOT = Path(SPECPATH) / ".." / "Flow-AI_open" / "src"
TEMPLATES_DIR = Path(SPECPATH) / ".." / "Flow-AI_open" / "src" / "flow_ai_open" / "templates"

# 使用 collect_all 收集 pydantic 的所有子模块、数据文件和二进制文件（比逐个列出更健壮）
pydantic_datas, pydantic_binaries, pydantic_hiddenimports = collect_all("pydantic")

a = Analysis(
    # sidecar_main.py 作为主入口点（app_main.py 为辅助入口）
    [str(Path(SPECPATH) / "sidecar_main.py"), str(Path(SPECPATH) / "app_main.py")],
    pathex=[
        str(FLOW_AI_ROOT),
        str(FLOW_AI_OPEN_ROOT),
    ],
    binaries=pydantic_binaries,
    datas=[
        (str(TEMPLATES_DIR), "flow_ai_open/templates"),
        (str(Path(SPECPATH) / ".." / "Flow-AI" / "src" / "flow_ai" / "classifier" / "configs"), "flow_ai/classifier/configs"),
    ] + pydantic_datas,
    hiddenimports=[
        "sidecar_main",
        "flow_ai",
        "flow_ai.core",
        "flow_ai.core.ast_models",
        "flow_ai.core.enums",
        "flow_ai.core.style_models",
        "flow_ai.core.profile_models",
        "flow_ai.core.preservation_models",
        "flow_ai.core.text_chunker",
        "flow_ai.contracts",
        "flow_ai.contracts.classification_contracts",
        "flow_ai.contracts.draft_decisions_v3",
        "flow_ai.contracts.error_codes",
        "flow_ai.contracts.status_shell",
        "flow_ai.classifier",
        "flow_ai.classifier.classifier_models",
        "flow_ai.classifier.evidence_classifier",
        "flow_ai.classifier.heading_binder",
        "flow_ai.classifier.pattern_probe",
        "flow_ai.classifier.regex_classifier",
        "flow_ai.classifier.run_classifier",
        "flow_ai.classifier.structure_resolver",
        "flow_ai_open",
        "flow_ai_open.adapters",
        "flow_ai_open.adapters.core_adapter",
        "flow_ai_open.adapters.patch_merger",
        "flow_ai_open.adapters.session_manager",
        "flow_ai_open.engine",
        "flow_ai_open.engine.rule_engine",
        "flow_ai_open.engine.yaml_loader",
        "flow_ai_open.ingestion",
        "flow_ai_open.ingestion.docx_parser",
        "flow_ai_open.pipeline",
        "flow_ai_open.pipeline.ast_projection",
        "flow_ai_open.renderer",
        "flow_ai_open.renderer.docx_renderer",
        "flow_ai_open.templates",
        "flow_ai_open.utils",
        "flow_ai_open.utils.typography_cn",
        # --- Phase2: flow_ai.format 格式识别引擎 ---
        "flow_ai.format",
        "flow_ai.format.extractor",
        "flow_ai.format.knowledge_base",
        "flow_ai.format.ast_reader",
        "flow_ai.format.ast_intent_builder",
        "flow_ai.format.slot_aligner",
        "flow_ai.format.format_clusterer",
        "flow_ai.format.semantic_anchor",
        "flow_ai.format.style_resolver",
        "flow_ai.format.visual_fingerprint",
        "flow_ai.format.visual_weight",
        # --- Phase2: flow_ai.contracts 新增 ---
        "flow_ai.contracts.format_catalog",
        # --- Phase2: flow_ai.classifier 新增 ---
        "flow_ai.classifier.arbitration",
        "flow_ai.classifier.context_stack",
        "flow_ai.classifier.doc_type_router",
        "flow_ai.classifier.naked_probe",
        "flow_ai.classifier.phase0_hygiene",
        "flow_ai.classifier.phase3_pipeline",
        "flow_ai.classifier.pipeline_models",
        "flow_ai.classifier.structural_track",
        "flow_ai.classifier.visual_track",
        # --- Phase1/2: flow_ai_open 新增 ---
        "flow_ai_open.config_loader",
        "flow_ai_open.telemetry",
        "flow_ai_open.telemetry.supabase_client",
        "flow_ai_open.typography_defaults",
        "flow_ai_open.templates.format_extractor",
        "flow_ai_open.templates.docx_template_extractor",
        "flow_ai_open.templates.style_resolver",
        "flow_ai_open.ingestion.body_block_parser",
        "flow_ai_open.ingestion.body_text",
        "flow_ai_open.ingestion.comment_reader",
        "flow_ai_open.ingestion.coverage_report",
        "flow_ai_open.ingestion.document_resources",
        "flow_ai_open.ingestion.footnote_reader",
        "flow_ai_open.ingestion.header_footer_reader",
        "flow_ai_open.ingestion.ooxml_inventory",
        "flow_ai_open.ingestion.story_part_utils",
        "flow_ai_open.tasks",
        "flow_ai_open.tasks.task_manager",
        "pydantic",
        "pydantic.deprecated",
        "pydantic.deprecated.decorator",
        "lxml",
        "lxml._elementpath",
        "lxml.etree",
        "yaml",
    ] + pydantic_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "unittest",
        "test",
        "tests",
        "pytest",
        "numpy",
        "scipy",
        "matplotlib",
        "PIL",
        "Pillow",
        "email",
        "html",
        "xml.dom",
        "multiprocessing",
        "concurrent",
        "asyncio",
        "setuptools",
        "pip",
        "wheel",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="Flow-AI-sidecar",
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
