from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    E_INVALID_AST = "E_INVALID_AST"
    PARSE_FAILED = "PARSE_FAILED"
    CLASSIFY_FAILED = "CLASSIFY_FAILED"
    RENDER_FAILED = "RENDER_FAILED"
    E_PARSE_FAILURE = PARSE_FAILED
    E_CLASSIFICATION_FAILURE = CLASSIFY_FAILED
    E_RENDER_FAILURE = RENDER_FAILED
    E_INTERNAL_ERROR = "E_INTERNAL_ERROR"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    PATCH_CONFLICT = "PATCH_CONFLICT"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
